### PR TITLE
Remove the Splash-Screen

### PR DESCRIPTION
**Pull request by ligi**
Was thinking to add it to the Remove-Clutter PR - but isolating it as it is a functional change here.
Splash-Screens are one UX anti-pattern - especially when there is no loading done in this case - the user is just blocked for 1s+ without any reason

### CODE REVIEW

**Comment by stephanlindauer** [comment]
valid point. back then i couldnt resist the temptation to show off our amazing logo. :)
any other opinions?

**Comment by cbalster** [comment]
but..but.. the logo!
No, seriously - I also think it should be removed. Maybe we can find a nice spot for the logo somewhere else - maybe in a redesigned about tab?. Would be a shame not to use it :)

**Comment by stephanlindauer** [comment]
2 against 1...
i surrender! ;)

**Comment by ligi** [comment]
Great! You did the right thing - big day for the UX of criticalmaps. We will find a nice place to show of the logo ;-)

**Pull request merged**
