### PR TITLE
Dry alertdialog builder

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by cbalster** [comment]
:+1:

**Comment by ligi** [comment]
:+1: this is a nice change - additionally we should use the AlertDialog
from support-v7

On 06.10.2015 14:37, Christian Balster wrote:
> :+1: 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/criticalmaps/criticalmaps-android/pull/59#issuecomment-145843522
> 


-- 
best regards,
ligi
http://ligi.de

**Comment by cbalster** [comment]
+1 for v7 alertdialog - would prefer this in a separate commit though.

**Comment by ligi** [comment]
as I know tobi he would refuse to do it otherwise - just saw it here
that we still use the native AlertDialogs ;-)

On 06.10.2015 14:40, Christian Balster wrote:
> +1 for v7 alertdialog - would prefer this in a separate commit though.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/criticalmaps/criticalmaps-android/pull/59#issuecomment-145844527
> 


-- 
best regards,
ligi
http://ligi.de

**Pull request merged**
