### PR TITLE
Update Gradle plugin to v.1.5.0.

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by ligi** [comment]
let's wait with this until https://github.com/square/spoon/issues/300 is resolved

**Comment by johnjohndoe** [comment]
@ligi Sure. No problem.

**Comment by johnjohndoe** [comment]
@ligi Is Spoon ready meanwhile?

**Comment by stephanlindauer** [comment]
looks like they released it right one day after @ligi suggested to wait for the release :)

**Comment by ligi** [comment]
Yes it is out now - we might now even go to 2.0.0-alpha3 - instant-run is pretty nice - the only draw-back I see currently is that you have to get a newer version from sdkmanager through jitpack.io

**Comment by johnjohndoe** [comment]
I am using alpha and beta version locally, too. I would not commit them in this case, though.

**Comment by ligi** [comment]
Was just saying as @cbalster was suggesting it here https://github.com/criticalmaps/criticalmaps-android/pull/134 and I blocked at this time - but I think with alpha3 it got pretty useable and I gained some confidence in this plugin

**Comment by johnjohndoe** [comment]
Rebased.

**Comment by ligi** [comment]
:+1:

**Pull request merged**
