### PR TITLE
Chat fragment with FAB and textinputlayout

### PR DESCRIPTION
**Pull request by ligi**
this also introduces the character counting: https://www.google.com/design/spec/components/text-fields.html#text-fields-full-width-text-field

### CODE REVIEW

**Comment by cbalster** [comment]
like it a lot! one issue though: I'm not exactly sure this the right usage of a FAB. As the name says it's usually "floating". Compared to the usage in other apps this doesn't really fit since it's used like a normal button.

**Comment by ligi** [comment]
AFAIK it is the right usage of a FAB - sending the message is the main-action in this view

**Comment by cbalster** [comment]
If you look at the common usage of it, it's more for navigating to the main action of the current activity - like a shortcut. But we already have that main action right there - the edittext. The way it's used tight now is just like a regular button.

**Comment by ligi** [comment]
Look at google-hangouts - they are doing exactly the same thing - their FAB is just smaller and green

**Comment by cbalster** [comment]
I wouldn't call that proper usage of the fab either ;)
IMHO the name implies it all "floating" as in floating above and on top of the rest of the UI ("They are distinguished by a circled icon floating above the UI"). Especially when above a listview that's scrolled etc.
Here (and in hangouts) it's just a static part of a standard layout, that doesn't change at all and just fulfills the role of a plain old button.
If you look at all the examples at https://www.google.com/design/spec/components/buttons-floating-action-button.html there is no example where it's used like that.

**Comment by ligi** [comment]
I stilö think it is a perfect use-case for a FAB and nothing in the
design-document tells me it's not - just not there as an example.
Let's see what the others think - and you can make a alternative if you
want.
The FAB is floating as it has elevation - and it is round to catch
attention in a rectangular world ( phone )

On 16.10.2015 17:40, Christian Balster wrote:
> I wouldn't call that proper usage of the fab either ;)
> IMHO the name implies it all "floating" as in floating above and on top
> of the rest of the UI ("They are distinguished by a circled icon
> floating above the UI"). Especially when above a listview that's
> scrolled etc.
> Here (and in hangouts) it's just a static part of a standard layout,
> that doesn't change at all and just fulfills the role of a plain old button.
> If you look at all the examples at
> https://www.google.com/design/spec/components/buttons-floating-action-button.html
> there is no example where it's used like that.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/criticalmaps/criticalmaps-android/pull/95#issuecomment-148749870>.
> 


-- 
best regards,
ligi
http://ligi.de

**Comment by cbalster** [comment]
Okay, I just took another look at other messenger apps and indeed a lot of people tend to use it that way. So I stand corrected :)
Just two more suggestions then: Maybe we can also make it smaller - for example on my device it makes the whole textinput part quite a lot higher then it'd need to be. And a really nice touch would be to grey it out until some text has been entered - maybe even with a nice animation.

**Comment by cbalster** [comment]
oh, and besides that everything looks good to me :+1:

**Comment by ligi** [comment]
:+1: updated the PR - smaller FAB and animation depending size>0

**Pull request merged**
