### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by cbalster**
second commit only adds the strings to simplify updating the translations later

### CODE REVIEW

**Comment by ligi** [comment]
ack @ 28d1831
regarding the missing translations I would only add when we really have a translation - not duplicating the en version as this is used as fallback anyway

**Comment by cbalster** [comment]
I added the English versions to make it easier for the people doing the
translations to identify the missing strings. I planned to @ them in an
issue after this is merged.

**Comment by ligi** [comment]
I would suggest we use a translation management service like transifex
for this.

**Comment by cbalster** [comment]
I know and I think we already planned to set it up but no one ever did ;)

**Comment by ligi** [comment]
I ( think *1 ) I can set it up if wanted @stephanlindauer - would really prefer the placeholders to be there than rather in the xml's

*1 - have to check if this is possible as contributor to a project or if you have to be owner

**Comment by stephanlindauer** [comment]
@cbalster i agree with ligi to not add english strings to languages where we don't have a translation for yet. 
in case it's missing it will fall back to english anyway and in android studio its easier to spot missing translation if we don't add them.
however +1 on the first commit.
@ligi i tried transifex but i wasn't properly convinced due to the fact the there was still some manual labour involved to pull in the strings. also i think its nice to have everything in one place (github) without external dependencies. but i don't have such a strong opinion in this. if you want to set it up, juts go ahead. i will supply you with the necessary rights.

**Comment by ligi** [comment]
@stephanlindauer there is a tool called tx - so usually this is the workflow then:

> tx pull
> git commit -a -m "Update translations"

**Comment by stephanlindauer** [comment]
@ligi https://www.transifex.com/criticalmaps/critical-maps/

**Comment by stephanlindauer** [comment]
let's maybe take this discussion to https://github.com/criticalmaps/criticalmaps-android/issues/180

regarding this pr: i would merge if the second commit would be reverted.

**Comment by cbalster** [comment]
second commit removed and rebased on top of develop

**Pull request merged**
