### PR TITLE
Add test for SHA1 calculation

### PR DESCRIPTION
**Pull request by ligi**

### CODE REVIEW

**Comment by stephanlindauer** [comment]
+1 for our first test :)

**Comment by ligi** [comment]
yea - thought it might be good to have a basic test infrastructure -
makes it easier to add new ones later on ;-)
Also started with this function because there was doubt once that it
works:
https://github.com/ligi/criticalmaps-android/commit/009277148ceede8c77e4f9f2f29a0c685a55f8ab#commitcomment-13750715
The test proves it does ;-)
On 14.10.2015 17:50, stephan lindauer wrote:
> +1 for our first test :)
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/criticalmaps/criticalmaps-android/pull/76#issuecomment-148093504>.
> 


-- 
best regards,
ligi
http://ligi.de

**Comment by stephanlindauer** [comment]
coolio. i am getting travis ready for testing then.

**Comment by ligi** [comment]
Unit-tests like this one  will already executed by gradle clean build -
for instrumentation-tests this is a totally other story ..

On 14.10.2015 18:18, stephan lindauer wrote:
> Merged #76 <https://github.com/criticalmaps/criticalmaps-android/pull/76>.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/criticalmaps/criticalmaps-android/pull/76#event-435400758>.
> 


-- 
best regards,
ligi
http://ligi.de

**Comment by stephanlindauer** [comment]
ah ok. i didnt know that. well in that case i'll do nothing. :)

**Pull request merged**
