### PR TITLE
Transparent side drawer

### PR DESCRIPTION
**Pull request by stephanlindauer**
continuation of https://github.com/criticalmaps/criticalmaps-android/pull/121

### CODE REVIEW

**Comment by stephanlindauer** [comment]
thx! turned out i didn't see that button because i wasn't logged in. thought they removed it.

**Comment by ligi** [comment]
Great! would merge it  but please remove the space and squash

**Comment by stephanlindauer** [comment]
done

**Comment by ligi** [comment]
merged

**Pull request merged**
