### PR TITLE
Simplify usage of shared preferences.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ Inject shared preferences.
+ Please note that former setting will NOT be restored since
  preferences keys change in this commit. See SharedPrefKeys.java.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@stephanlindauer Any opinion about this? I can rebase this once again.

**Comment by stephanlindauer** [comment]
i am still feeling pretty vague about this pr. i'd say it makes the code just slightly easier to read but on the down side it introduces a new dependency.
@ligi @cbalster what do you think?

**Comment by ligi** [comment]
I am neither Pro nor Contra this PR

**Comment by cbalster** [comment]
Let's get it in. Can you rebase this again and take care of the injection
of shared preferences regarding the recent changes?

**Comment by johnjohndoe** [comment]
Rebased.

**Comment by cbalster** [comment]
:+1:

**Pull request merged**
