### PR TITLE
Opening the Drawer closes the Keyboard

### LINKED ISSUE #107: Chat - hide keyboard on drawer open
This ain't pretty

device-2015-10-24-172519

### PR DESCRIPTION
**Pull request by ligi**
closes #107

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@ligi Any chance to hide the keyboard earlier? I tested this fix on an emulator. The keyboard hides after the drawer has opened as one would expect from `onDrawerOpened`. So for a moment the keyboard is shown above the drawer, which is not optimal.

P.S. Please rebase onto master.

**Comment by ligi** [comment]
This branch is up-to-date with the base branch
Merging can be performed automatically.

Not sure if a earlier closing is needed - tested on a real device and it felt good to me

**Comment by johnjohndoe** [comment]
My emulator on my old notebook might be the equivalent to an older or cheap device with less power.

**Comment by ligi** [comment]
I would stick to closing the keyboard once the drawer is open - emulators rarely help getting the feeling of an app - especially for touch interactions with the device.

**Comment by stephanlindauer** [comment]
how about using ```onDrawerStateChanged(int newState)``` ?

**Comment by ligi** [comment]
I am still convinced that the time after the drawer is opened is the
right time as it is action->reaction. Otherwise a small bezel-touch
could cause a keyboard close

On 31.10.2015 13:36, stephan lindauer wrote:
> how about using |onDrawerStateChanged(int newState)| ?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/criticalmaps/criticalmaps-android/pull/109#issuecomment-152732842>.
> 


-- 
best regards,
ligi
http://ligi.de

**Comment by stephanlindauer** [comment]
convinced :)

**Pull request merged**
