### PR TITLE
Handle deprecations and slight ui update

### PR DESCRIPTION
**Pull request by cbalster**
This mainly handles deprecated code (minor changes), but also switches to AppCompatActivity with a TabLayout. This adds a hint of material design of the app and could be the base for further "materialization". Any thoughts and opinions?
screenshot_2015-10-01-20-37-57
screenshot_2015-10-01-20-37-41

### CODE REVIEW

**Comment by ligi** [comment]
:+1: looks good - also interesting to hear about CPU_ABI2 - would love to know which devices have 2 different ABI's ..-)

**Comment by cbalster** [comment]
afaik, ABI2 this is used for example on x86 devices that have arm translation libraries like libhoudini

**Comment by ligi** [comment]
ah - I thought this might be for power saving processor + powerful processor combinations

**Comment by cbalster** [comment]
Now that you mention probably on those too. :)

**Pull request merged**
