### PR TITLE
Add floating action button for twitter

### LINKED ISSUE #117: twitter: floating action button to trigger new tweet intent

### PR DESCRIPTION
**Pull request by stephanlindauer**
resolves #117

### CODE REVIEW

**Comment by ligi** [comment]
Looks good :+1: would merge - do you want to squash first?

**Comment by stephanlindauer** [comment]
i personally wouldn't. mainly because then we would lose the comments and references to them.
but i don't mind either way.

**Comment by ligi** [comment]
Your choice - merged

**Comment by ligi** [comment]
:+1:

**Comment by cbalster** [comment]
:+1: 
One thing though: Any good idea how to not obstruct a tweet, especially if you cannot scroll to make it visible? I know this is kind of an edge case to have exactly that amount of tweets, but still.
device-2015-12-27-144403

**Comment by stephanlindauer** [comment]
hide when list is scrolled all the way to the bottom?

**Comment by ligi** [comment]
A problem might be when the list is not scrollable, but full ..

**Comment by cbalster** [comment]
alternatively hide it after list has not beend scrolled for ~1 sec?

**Comment by cbalster** [comment]
or ignore that problem, just like hangouts does ;)

**Comment by ligi** [comment]
Just to bring another option to the table ( think we can ignore this for now ): we might reorganize the layout this way that it only hides date/time/avatar - no values with real content

**Comment by cbalster** [comment]
:+1: yes, after some thought I think we can safely ignore this minor issues - you can still open the tweet externally if something important is obstructed.

**Comment by stephanlindauer** [comment]
+1 for reorganizing the layout as ligi said

**Pull request merged**
