### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by cbalster**

### CODE REVIEW

**Comment by stephanlindauer** [comment]
merging this pr would make https://github.com/criticalmaps/criticalmaps-android/pull/131 obsolete, right?

**Comment by ligi** [comment]
Sure we want to use an alpha build-plugin here? And for this removing the nice sdkmanager - a patch for this problem is already committed - I would vote for not merging this

**Comment by cbalster** [comment]
As I said in the commit message qwe can bring back sdkmanager when the fix is in the release. Regarding the gradle plugin: It's required to use instant run in the android studio 2.0 preview (and it's an awesome feature btw) and everything works smoothly so far. But if you're against it I don't mind keeping these changes local for now.

**Comment by ligi** [comment]
I would vote for keeping this local for now. I do not yet have
confidence in the new plugin - though I have to say instant-run is nice
- but even without it write->run cycles got way faster

**Comment by cbalster** [comment]
so let's at least update build tools and support libs :)

**Comment by ligi** [comment]
:+1

**Pull request merged**
