### PR TITLE
Add application screenshot.

### PR DESCRIPTION
**Pull request by johnjohndoe**
I like to have a visual idea of an application/project when I study its description. I consider it as helpful when at least a screenshot of the application is shown.

### CODE REVIEW

**Comment by ligi** [comment]
Not a big fan of putting screenshots in the repo - but I like the idea of putting one in the README. Perhaps the screenshots can be put onto criticalmaps.net ( @stephanlindauer is this possible? )

**Comment by johnjohndoe** [comment]
@stephanlindauer Any opinion about the screenshot in the README?

**Comment by stephanlindauer** [comment]
either way is ok with me. but maybe ligi is right that android code repos should be only for androidd code and assets that actually are used. i can put that screen on the webserver oooor we create another repo where we keep files like that along with assets and copy for the play store for example. "criticalmaps-misc" or so. what do you think?

**Comment by stephanlindauer** [comment]
as a sidenote: i should and will update the google play store assets real soon.

**Comment by cketti** [comment]
You could use [Github project pages](https://help.github.com/articles/creating-project-pages-manually/) to host the images.

However, keeping screenshots that are referenced from the README inside the repository has the advantage that they are versioned together, not separately. I think that's a big win.

**Comment by johnjohndoe** [comment]
Agreed with @cketti. I consider the repository the source of all project relevant files. Therefore, I would **not** store the textual and visual description of the project in **separate** locations.

**Comment by ligi** [comment]
I can understand the urge to have everything in one place - was also
doing this for a while. But it comes with a high price: Everyone who
wants to clone your repo to just build the app ( e.g. FDroid, CI,
potential contributors ) have to download all versions from all
Screenshots which they will never use. As far as I know there is no way
to remove the binaries from the project without loosing the whole
history. Perhaps git-lfs is an option. But when doing it as in this PR I
think the disadvantages outweigh the advantages.

On 12.10.2015 11:03, Tobias Preuss wrote:
> Agreed with @cketti <https://github.com/cketti>. I consider the
> repository the source of all project relevant files. Therefore, I would
> *not* store the textual and visual description of the project in
> *separate* locations.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/criticalmaps/criticalmaps-android/pull/56#issuecomment-147336186>.
> 


-- 
best regards,
ligi
http://ligi.de

**Comment by johnjohndoe** [comment]
> ... Everyone who wants to clone your repo to just build the app ...

In cases where the history is not of interest one could easily clone just the latest version:

``` bash
$ git clone --depth=1 <repository-url>
```

**Comment by cketti** [comment]
@ligi: That sounds like premature optimization. We're talking about a few megabytes, not gigabytes.

**Comment by ligi** [comment]
Megabytes matter !-) You do not really see the problem in Germany - but not all countries have such a good connectivity - I remember times when I was traveling and aborting a clone to fix a small bug because it just took too long ..
@cketti - it might be premature but in this case there is no way to optimize later

**Comment by stephanlindauer** [comment]
lets just put this to a vote, shall we?
i think the options are:
- this repo?
- seperate orga repo?
- webserver?
- github project pages?
- don't use a screenshots in the readme at all?
@cketti @johnjohndoe @ligi @cbalster

**Comment by ligi** [comment]
I would vote for separate media/orga-repo

**Comment by cketti** [comment]
This repo.

I see the point of making the repository more accessible to people with slow connections. But right now that's only a theoretical issue. If it becomes a real problem there are ways to create a new repository with the complete history of this one excluding some files/directories, e.g. screenshots.

**Comment by cbalster** [comment]
I don't really care to much, but I lean to ligi's side. BUT that ship kinda
sailed already as we already have ~30 megs of assets in /misc.
So maybe we can just merge this and get back to cketti's suggestion
"later". Oh and regarding the screenshot itself: Maybe it should show a
mapview with other riders, as that would give a better impression of what
the app looks like in use.

**Comment by stephanlindauer** [comment]
@cbalster yep. the misc/ folder would have to move as well.
i vote for "seperate orga repo"

**Comment by ligi** [comment]
@cketti would really know how this would work - did not know there is a way to do this without loosing history - if there is one I would also be OK with sailing this path a bit longer ;-)

**Comment by cbalster** [comment]
@cketti But this will result in a rewritten history and a force push with
all it's consequences, right? I mean the ID of the commits are based on the
content and if that changes...

**Comment by ligi** [comment]
He just gave me this link in a chat ( https://git-scm.com/docs/git-filter-branch ) - sounds good - will give it a try - learned something new ;-)

**Comment by cketti** [comment]
@cbalster: Yes, it would of course be a different history.

**Comment by cbalster** [comment]
Yeah, okay. So if we do that, let's do it now. The longer we wait the more
we're gonna confuse people that forked the repo. Also you might want to
take a look at BFG for that.

**Comment by cbalster** [comment]
https://rtyley.github.io/bfg-repo-cleaner/
Never used it but seems to make it easier/faster :)

**Comment by ligi** [comment]
very cool:

".. The BFG treats you like a reformed alcoholic: you've made some mistakes in the past, but now you've cleaned up your act. Thus the BFG assumes that your latest commit is a good one, with none of the dirty files you want removing from your history still in it. This assumption by the BFG protects your work, and gives you peace of mind knowing that the BFG is only changing your repo history, not meddling with the current files of your project. .."

will try that out when I get home - sounds really good - love it when I learn something new ;-) just not sure how to best do it process-wise - all PR's should be merged and there should be like a one week warning to all before doing it so that people do not end up with half baked PR's against the old history

**Comment by cbalster** [comment]
I agree, it would be best to get all PRs merged/sorted out before. IMHO the
warning time is not so important as any non published WIP commits should be
easy to carry over by cherry-picking or git am'ing if I'm not missing
something here.

**Comment by johnjohndoe** [comment]
Resolved in #72

**Pull request closed without merging**
