### PR TITLE
Update project setup

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by cbalster** [comment]
Hey, I actually wanted to suggest to bump compileSdkVersion to 22 and bring the support library version in line with it by setting it to 22.2.1

**Comment by johnjohndoe** [comment]
@cbalster Agreed. The versions should be in line. If you do not want to update to v.23 - then that is fine.

**Comment by cbalster** [comment]
As the apache http libraries have been removed there, updating to 23 is not possible. I think this actually not a big deal for now since it doesn't bring anything relevant otherwise.

**Comment by ligi** [comment]
another possibility is to use  useLibrary 'org.apache.http.legacy'

**Comment by cbalster** [comment]
yep, which is probably the better solution - especially if 23+ brings relevant changes.
But considering that google isn't maintaining it's httpclient fork anymore, one should probably switch to something else in the long run.

**Comment by johnjohndoe** [comment]
Side note: [Issue #3001](https://code.google.com/p/android-developer-preview/issues/detail?id=3001) might be worth following if you planning to use Google Play Services somewhen.

**Comment by stephanlindauer** [comment]
hey guys, sorry, i am struggeling to find time to look at pull requests lately.
are you on the same page regarding this PR? should i merge?
please excuse my brevity. i will probably be less busy by mid october.
maybe we should move this project to a github organisation of which we are all members more than just me can merge PRs. i will discuss this with @headione as soon as i meet him again and let you know.

**Comment by rodrigoaguilera** [comment]
I hope this project doesn't include in the future a proprietary software dependency like google services.

**Comment by ligi** [comment]
@rodrigoaguilera :+1: there should always be at least one flavor that is FDroid compatible 
@stephanlindauer this is a trivial change - very easy to rebase - no hurry on this
@cbalster totally agree - in the end deprecated stuff should not be used anymore okhttp / okio is a nice option for some of it

**Comment by johnjohndoe** [comment]
Okay. I will downgrade `com.android.support:support-v4:23.0.0` to the latest v.22 which is `com.android.support:support-v4:22.2.1`. I will rebase and force push the change on this branch. Agreed?

**Comment by ligi** [comment]
:+1:

**Comment by cbalster** [comment]
:+1: Can you also bump compileSdkVerion to 22 while you're at it?
Just as a heads up: I already have some patches ready to replace most of the deprecated stuff (except for the http stuff). I will rebase and push them once this is merged.

**Comment by stephanlindauer** [comment]
i created the organization and added all of you into it. so now you have write access. 
please still always develop on a separate branch and then make pull requests to master. a second person from that team should then have a look and merge that pull request. 4 eye principle. sounds reasonable?

**Comment by cbalster** [comment]
yes, sounds good to me, thanks. :+1:

**Comment by ligi** [comment]
Created a PR to move to OKHttp - now we can use SDK23

**Pull request merged**
