### PR TITLE
Styles and themes

### PR DESCRIPTION
**Pull request by cbalster**
Most of this is preparation for further materialization - more to come....
This also changes the colors a bit, I tried to compromise between what we have and the material guidelines here. Screenshot of what it looks like on API 22:
device-2015-10-16-141211

### CODE REVIEW

**Comment by ligi** [comment]
Looks good! Will merge when travis is happy - especially like the coordinates in the screenshot ;-)

**Comment by cbalster** [comment]
credits to the location go to genymotion - made me smile when I first used
it ;)

**Comment by ligi** [comment]
:+1:

**Comment by stephanlindauer** [comment]
nice!

**Pull request merged**
