### PR TITLE
rework image upload + misc

### PR DESCRIPTION
**Pull request by cbalster**

### CODE REVIEW

**Comment by cbalster** [comment]
Only tested against local server and not the live api, but I don't see any reason it shouldn't work.

**Comment by ligi** [comment]
:+1: Looks good to me - but I think @stephanlindauer should look over and merge this one because he knows more about the server-part ..

**Comment by stephanlindauer** [comment]
looks good. have you tested against that php file?
if not, let me test before merging. will try to do that on the 23rd.

**Comment by cbalster** [comment]
@stephanlindauer yes, I did test it using the actual API. I commented out the DB calls though, but logged the values for lat/long to make sure they are correct.

**Comment by stephanlindauer** [comment]
:+1:
works.
really nice to get rid of all that clutter.

**Pull request merged**
