### PR TITLE
Remove the tweet user-image loading progress-bar after loading

### PR DESCRIPTION
**Pull request by ligi**
Otherwise the progress-bar still consumes CPU-Cycles and will make problems with espresso-testing

### CODE REVIEW

**Comment by cbalster** [comment]
Looks good. Two issues though:
1) quote from the docs: "Note: The Callback param is a strong reference and will prevent your Activity or Fragment from being garbage collected. If you use this method, it is strongly recommended you invoke an adjacent Picasso.cancelRequest(android.widget.ImageView) call to prevent temporary leaking."
2) If we don't do that and the views have been destroyed before the callback is executed, we will get an NPE

**Comment by ligi** [comment]
Well spotted! Will do the NPE check - what do you think about the leak? it is not living that long so it should be all right - and cancelling the request will get really ugly here

**Comment by cbalster** [comment]
I think we can live with it. And I remember reading something about Picasso having a watcher thread automatically canceling requests that are not needed anymore.

**Comment by ligi** [comment]
OK added the check - whill squash when you are ready to merge

**Comment by cbalster** [comment]
:+1:

**Comment by ligi** [comment]
squashed

**Comment by stephanlindauer** [comment]
everytime i see "squashed", i read "squanched" and have to think of 
https://www.youtube.com/watch?v=qA15dUNe2z8

**Pull request merged**
