### PR TITLE
Add ScreenShot from media repo

### PR DESCRIPTION
**Pull request by ligi**
Based on @johnjohndoe 's PR with screenshot from media repo

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Related: #56

**Comment by ligi** [comment]
Maybe we should also add the nice logo here - ref. #51

**Comment by cbalster** [comment]
:+1: Let's just merge it and do additions in new commits

**Comment by stephanlindauer** [comment]
:+1:

**Comment by stephanlindauer** [comment]
i just fixed the markup so its an image now. it was supposed to be referenced as am , right?

**Comment by ligi** [comment]
am?
I just took tobis PR and changed the URL ..-)

**Comment by stephanlindauer** [comment]
ok. so the way it is roght now on master is the way its supposed to be right?

**Comment by cbalster** [comment]
I'd say so :)

**Comment by stephanlindauer** [comment]
ok perfect. so much confusion around this whole screenshot topic... :D

**Comment by cbalster** [comment]
yep, can of worms - from simple doc change to force pushing a new history
in only a single PR :D

**Pull request merged**
