### PR TITLE
Observer mode and ui rework

### PR DESCRIPTION
**Pull request by cbalster**
- adds observer mode (explanation still missing)
- updated to the new MaterialComponent theming mechanism and updated colorscheme and layouts 

**Launch**
screenshot_1549712035
**Intro**
screenshot_1549712043
**Map**
screenshot_1549712050
**Menu**
screenshot_1549712056
**Chat**
screenshot_1549712070
screenshot_1549712077
**Twitter**
screenshot_1549712087
**Rules**
screenshot_1549712095
screenshot_1549712098
**Settings**
screenshot_1549712102
**About**
screenshot_1549712109
screenshot_1549713493

### CODE REVIEW

**Comment by zutrinken** [comment]
bildschirmfoto 2019-02-09 um 16 25 56

Since I can't test it right now: Why do we need two locate icons? Or what does the left one do?

**Comment by cbalster** [comment]
> Actionbar title alway shows "Critical Maps" instead of the current view.

Good Point. Even though it's not too uncommon for single activity apps, I think it's better to show the current screen's name.

> Since I can't test it right now: Why do we need two locate icons? Or what is the left one doing?

The left one shows map orientation and resets it to north on click. Right one centers location and also acts as a GPS status indicator (normal, searching, gps disabled).

**Comment by zutrinken** [comment]
I'd give the observer mode a little more context. Some small description and a different icon. A car might be a good choice to point out that's a feature for different types of vehicles:



Or a ghost. That just looks cute:

**Comment by cbalster** [comment]
> Or a ghost. That just looks cute:
> 
> 

Love the ghost!

> I'd give the observer mode a little more context. Some small description and a different icon. A car might be a good choice to point out that's a feature for different types of vehicles:

Yes, that's exactly what I had in mind! Unfortunately the default android NavigationView component doesn't allow for that kind of customization, as the're using a FrameLayout and a RecyclerView with fixed layouts under the hood. This basically means re-writing that part which I will do, but don't really have the time to right now.

**Comment by cbalster** [comment]
Added an acceptable workaround for adding the description.
Not quite happy with the icon on the map though - putting it in a circle would be consistent, but hard to recognize I guess.

image

image

**Comment by cbalster** [comment]
Added icons by @zutrinken 

image

image

**Comment by cbalster** [comment]
As soon as you implemented the server side part for observer mode ;)
No, I think it would be ideal if the ios and android app both got observer
mode at the same time.

I also have another PR that's basically ready, which I will probably push
on Tuesday.

**Comment by stephanlindauer** [comment]
AFAIS the way this will work in the backend is that we will safe the locations of the observers as well but they wont be in the response to the clients, right? if the parameter is not there then we assume non-observer.
sounds like relatively simple change to me. i will put this in next weekend.

**Comment by cbalster** [comment]
Exactly, just a minor change.

**Pull request merged**
