### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by stephanlindauer**

### CODE REVIEW

**Comment by ligi** [comment]
Would squash e26944b and cbfb219
Other than that looks formally good - no Idea if the translations are correct though ..-)

**Comment by stephanlindauer** [comment]
sorry for being such a slacker when it comes to keeping the history clean. ;)
commits are squashed.
the italian should be fine. comes from the cm florence.

**Comment by stephanlindauer** [comment]
oh wait. forgot a proper commit message.

**Comment by stephanlindauer** [comment]
now :)

**Comment by ligi** [comment]
:+1: should we also redirect this to develop?

**Comment by stephanlindauer** [comment]
lets merge this one straight into master. i opened the pr before we decided to go with git flow and i don't think we need extensive testing for this one.

**Comment by ligi** [comment]
ack :+1: merged

**Comment by cbalster** [comment]
okay, so let's just treat this as a hotfix and also merge it into develop (which we have to do either way)

**Comment by stephanlindauer** [comment]
agreed.

**Comment by ligi** [comment]
Merged master into develop

On 10.11.2015 16:55, stephan lindauer wrote:
> agreed.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/criticalmaps/criticalmaps-android/pull/120#issuecomment-155462006>.
> 


-- 
best regards,
ligi
http://ligi.de

**Pull request merged**
