### PR TITLE
Simplify usage of shared preferences.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ Please note that former setting will NOT be restored since preferences keys
  are changed in this commit. See SharedPrefKeys.java.

### CODE REVIEW

**Comment by ligi** [comment]
Why don't we keep the old keys? Now it seems to me as the users will be presented with intro again and this is a regression in my eyes

**Comment by johnjohndoe** [comment]
I wrapped "latitude" and "longitude" in the `GeoPointPreference` class. Since this introduces a new preferences key I did not see any need to keep the former time stamp preference.

One could do a migration of the preference keys so it is transparent to the user. I however consider showing the intro once more as not that disturbing. Therefore, I would not do the migration.

**Comment by johnjohndoe** [comment]
@stephanlindauer Can you please decide whether it is okay for you show the welcome screen once or if this pull request cannot be merged the way it is now?

**Comment by stephanlindauer** [comment]
i would bow to the majority vote on this one. imho its not too bad to bother the user once more with that intro. maybe its even a good thing to remind users of whats in there.

**Comment by stephanlindauer** [comment]
@cbalster what are your thoughts on this one?

**Comment by johnjohndoe** [comment]
GitHub does not let me change this pull request to run against `develop`. Therefore, I had to open #132.

**Pull request closed without merging**
